#!/usr/bin/env python3
"""Turn ../v2-reference/vectors.json into a dependency-free C header.

The JSON stays the single source of truth; this only re-expresses it so the
test binary needs no JSON parser. Re-run whenever v2_frame.py --emit is re-run.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "v2-reference" / "vectors.json"
OUT = HERE / "vectors.inc"

v = json.loads(SRC.read_text())

lines = [
    "/* GENERATED by gen_vectors.py from ../v2-reference/vectors.json. Do not edit. */",
    "",
    'struct vcase {',
    '\tconst char   *name;',
    '\tunsigned char type;',
    '\tunsigned int  sender_id;',
    '\tunsigned int  counter;',
    '\tconst char   *payload_hex;',
    '\tconst char   *nonce_hex;',
    '\tconst char   *frame_hex;',
    '};',
    "",
    f'#define MASTER_KEY_HEX "{v["master_key_hex"]}"',
    f'#define VECTORS_SPEC   "{v["spec"]}"',
    f'#define EXPECT_FINGERPRINT "{v["fingerprint"]}"',
    "",
    "static const struct vcase CASES[] = {",
]
for c in v["cases"]:
    lines.append(
        '\t{{ "{name}", {type}, {sid}u, {ctr}u,\n'
        '\t  "{pl}",\n'
        '\t  "{nonce}",\n'
        '\t  "{frame}" }},'.format(
            name=c["name"], type=c["type"], sid=c["sender_id"], ctr=c["counter"],
            pl=c["payload_hex"], nonce=c["nonce_hex"], frame=c["frame_hex"]))
lines += ["};", ""]

OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({len(v['cases'])} cases)")
